const Datos = [
  // Jugadores de Baloncesto
 [ { id: 1, nombre: "LeBron James", deporte: "Baloncesto", equipo: "Los Angeles Lakers", valoracion: 5, equipo_url: "" ,posicion: "Alero", url: " " ,biografia: "LeBron James es un jugador versátil y dominante en el baloncesto. Ha ganado múltiples campeonatos y ha sido MVP de la NBA en varias ocasiones." },
  { id: 2, nombre: "Stephen Curry", deporte: "Baloncesto", equipo: "Golden State Warriors", valoracion: 5, equipo_url: "" ,posicion: "Base", url: " " ,biografia: "Stephen Curry es uno de los mejores tiradores en la historia del baloncesto. Ha ganado campeonatos y ha revolucionado el juego con su habilidad para realizar tiros de larga distancia." },
  { id: 3, nombre: "Kevin Durant", deporte: "Baloncesto", equipo: "Brooklyn Nets", valoracion: 5, equipo_url: "" ,posicion: "Ala-Pívot", url: " " ,biografia: "Kevin Durant es un jugador con una habilidad ofensiva excepcional. Ha ganado campeonatos y ha sido MVP de las Finales de la NBA." },
  { id: 4, nombre: "Giannis Antetokounmpo", deporte: "Baloncesto", equipo: "Milwaukee Bucks", valoracion: 5, equipo_url: "" ,posicion: "Ala-Pívot", url: " " ,biografia: "Giannis Antetokounmpo es un jugador atlético y dominante en la cancha. Ha ganado el MVP de la NBA y ha llevado a los Bucks al campeonato de la liga." },
  { id: 5, nombre: "Kawhi Leonard", deporte: "Baloncesto", equipo: "Los Angeles Clippers", valoracion: 4, equipo_url: "" ,posicion: "Alero", url: " " ,biografia: "Kawhi Leonard es conocido por su habilidad defensiva y capacidad para anotar en momentos clave. Ha ganado múltiples campeonatos y ha sido MVP de las Finales de la NBA." },
  { id: 6, nombre: "Luka Dončić", deporte: "Baloncesto", equipo: "Dallas Mavericks", valoracion: 4, equipo_url: "" ,posicion: "Base", url: " " ,biografia: "Luka Dončić es considerado una de las jóvenes estrellas en el baloncesto. Su habilidad para anotar y su visión de juego lo han convertido en un jugador destacado." },
  { id: 7, nombre: "Damian Lillard", deporte: "Baloncesto", equipo: "Portland Trail Blazers", valoracion: 4, equipo_url: "" ,posicion: "Base", url: " " ,biografia: "Damian Lillard es conocido por su habilidad para realizar tiros ganadores. Ha sido seleccionado varias veces para el All-Star y ha liderado la liga en bloqueos." },
  { id: 8, nombre: "Joel Embiid", deporte: "Baloncesto", equipo: "Philadelphia 76ers", valoracion: 4, equipo_url: "" ,posicion: "Pívot", url: " " ,biografia: "Joel Embiid es un jugador dominante en la pintura y un excelente defensor. Ha sido seleccionado varias veces para el All-Star y ha liderado la liga en bloqueos." },
  { id: 9, nombre: "Nikola Jokić", deporte: "Baloncesto", equipo: "Denver Nuggets", valoracion: 4, equipo_url: "" ,posicion: "Pívot", url: " " ,biografia: "Nikola Jokić es un jugador versátil y hábil en el baloncesto. Ha sido nombrado MVP de la NBA y ha llevado a los Nuggets a los playoffs en múltiples ocasiones." },
  { id: 10, nombre: "Anthony Davis", deporte: "Baloncesto", equipo: "Los Angeles Lakers", valoracion: 4, equipo_url: "" ,posicion: "Ala-Pívot", url: " " ,biografia: "Anthony Davis es un jugador atlético y dominante en ambos lados de la cancha. Ha ganado campeonatos y ha sido seleccionado para el All-Star en varias ocasiones." },
],
  // Jugadores de Fútbol
  [{ id: 11, nombre: "Lionel Messi", deporte: "Fútbol", equipo: "Paris Saint-Germain", valoracion: 5, equipo_url: "" ,posicion: "Delantero", url: " " ,biografia: "Lionel Messi es considerado uno de los mejores futbolistas de todos los tiempos. Ha ganado múltiples Balones de Oro y ha sido fundamental en los éxitos del Barcelona y la selección argentina." },
  { id: 12, nombre: "Cristiano Ronaldo", deporte: "Fútbol", equipo: "Manchester United", valoracion: 5, equipo_url: "" ,posicion: "Delantero", url: " " ,biografia: "Cristiano Ronaldo es un goleador excepcional y uno de los mejores futbolistas de la historia. Ha ganado numerosos títulos y ha dejado su huella en clubes como el Manchester United, el Real Madrid y la selección portuguesa." },
  { id: 13, nombre: "Neymar Jr.", deporte: "Fútbol", equipo: "Paris Saint-Germain", valoracion: 4, equipo_url: "" ,posicion: "Delantero", url: " " ,biografia: "Neymar Jr. es un talentoso jugador brasileño conocido por su habilidad en el regate y su capacidad para anotar. Ha ganado títulos de liga y ha sido una figura destacada en el Barcelona y el Paris Saint-Germain." },
  { id: 14, nombre: "Kylian Mbappé", deporte: "Fútbol", equipo: "Paris Saint-Germain", valoracion: 4, equipo_url: "" ,posicion: "Delantero", url: " " ,biografia: "Kylian Mbappé es una joven estrella del fútbol conocida por su velocidad y habilidad en el regate. Ha ganado títulos de liga y ha sido una pieza clave en el éxito del Paris Saint-Germain y la selección francesa." },
  { id: 15, nombre: "Mohamed Salah", deporte: "Fútbol", equipo: "Liverpool", valoracion: 4, equipo_url: "" ,posicion: "Delantero", url: " " ,biografia: "Mohamed Salah es un atacante rápido y goleador. Ha ganado títulos de liga y ha sido reconocido como uno de los mejores futbolistas en su posición." },
  { id: 16, nombre: "Virgil van Dijk", deporte: "Fútbol", equipo: "Liverpool", valoracion: 4, equipo_url: "" ,posicion: "Defensa", url: " " ,biografia: "Virgil van Dijk es un defensor sólido y líder en la cancha. Ha ganado títulos de liga y ha sido reconocido como uno de los mejores defensores del mundo." },
  { id: 17, nombre: "Robert Lewandowski", deporte: "Fútbol", equipo: "Bayern Munich", valoracion: 4, equipo_url: "" ,posicion: "Delantero", url: " " ,biografia: "Robert Lewandowski es un goleador implacable y uno de los mejores delanteros en el fútbol. Ha ganado títulos de liga y ha establecido récords goleadores en el Bayern Munich y la selección polaca." },
  { id: 18, nombre: "Kevin De Bruyne", deporte: "Fútbol", equipo: "Manchester City", valoracion: 4, equipo_url: "" ,posicion: "Centrocampista", url: " " ,biografia: "Kevin De Bruyne es un talentoso centrocampista conocido por su visión de juego y precisión en los pases. Ha ganado títulos de liga y ha sido clave en los éxitos del Manchester City y la selección belga." },
  { id: 19, nombre: "Sergio Ramos", deporte: "Fútbol", equipo: "Paris Saint-Germain", valoracion: 3, equipo_url: "" ,posicion: "Defensa", url: " " ,biografia: "Sergio Ramos es un defensor reconocido por su liderazgo y habilidad para marcar goles. Ha ganado múltiples títulos con el Real Madrid y la selección española." },
  { id: 20, nombre: "Manuel Neuer", deporte: "Fútbol", equipo: "Bayern Munich", valoracion: 3, equipo_url: "" ,posicion: "Portero", url: " " ,biografia: "Manuel Neuer es un arquero alemán considerado uno de los mejores en su posición. Ha sido una figura clave en el éxito del Bayern Munich y la selección alemana." },
]
  // Jugadores de League of Legends
 ,[ { id: 21, nombre: "Lee Sang-hyeok<br />(Faker)", deporte: "League of Legends", equipo: "T1", equipo_url: "https://esports.as.com/2019/10/08/SKT_Logo_2019.png?hash=22e270093357fb43b89c49697d29bfc2e5adcaab" ,posicion: "Midlaner", valoracion: 5, url: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Faker_2020_interview.jpg" ,biografia: "Faker es considerado el mejor jugador de League of Legends de todos los tiempos. Ha ganado múltiples campeonatos mundiales y ha sido una figura dominante en la escena competitiva." },
  { id: 22, nombre: "Jian Zi-Hao<br />(Uzi)", deporte: "League of Legends", equipo: "Retirado", equipo_url: "" ,posicion: "AD Carry", valoracion: 5, url: "https://esports.eldesmarque.com/wp-content/uploads/2018/10/Uzi.jpg " ,biografia: "Uzi es un reconocido jugador de AD Carry que ha dejado una gran impresión en la escena de League of Legends. Aunque se retiró, su legado sigue siendo relevante en la comunidad." },
  // { id: 23, nombre: "Kang Jun-hyeok<br />(TheShy)", deporte: "League of Legends", equipo: "Invictus Gaming", equipo_url: "" ,posicion: "Toplaner", valoracion: 5, url: "https://a1.espncdn.com/combiner/i?img=%2Fphoto%2F2019%2F0516%2Fr544093_1296x729_16%2D9.jpg " ,biografia: "TheShy es un talentoso Toplaner coreano conocido por su agresividad y mecánicas destacadas. Ha ganado el campeonato mundial de League of Legends." },
  // { id: 24, nombre: "Cho Se-hyeong<br />(BeryL)", deporte: "League of Legends", equipo: "DWG KIA", equipo_url: "https://esports.as.com/2021/09/29/DWG_KIAlogo_square.png?hash=3e554ecbaa2034e8515c56d6c6b3b0d160514f47" ,posicion: "Soporte", valoracion: 5, url: " " ,biografia: "BeryL es un destacado Soporte coreano que ha demostrado su habilidad en el escenario mundial. Ha sido campeón del mundo y ha recibido reconocimientos individuales." },
  { id: 25, nombre: "Rasmus Winther<br />(Caps)", deporte: "League of Legends", equipo: "G2 Esports", equipo_url: "https://esports.as.com/2020/01/27/G2_Esportslogo_square.png?hash=0fa5532caa9899d8f151aaad2783b2416fb57a42" ,posicion: "Midlaner", valoracion: 4, url: "https://www.theloadout.com/wp-content/sites/theloadout/2023/02/league-of-legends-lec-g2-caps-interview-winter-2023-groups.jpg " ,biografia: "Caps es un jugador europeo que ha tenido un impacto significativo en la escena de League of Legends. Ha ganado múltiples títulos regionales y ha competido en el escenario mundial." },
  // { id: 26, nombre: "Seung-lok Kang<br />(TheShy)", deporte: "League of Legends", equipo: "Invictus Gaming", equipo_url: "" ,posicion: "Toplaner", valoracion: 4, url: " " ,biografia: "TheShy es un jugador coreano conocido por su dominio en la posición de Toplaner. Ha sido campeón mundial y ha dejado una marca en la escena competitiva." },
  // { id: 27, nombre: "Luka Perković<br />(Perkz)", deporte: "League of Legends", equipo: "Cloud9", equipo_url: "" ,posicion: "Varios", valoracion: 4, url: " " ,biografia: "Perkz es un talentoso jugador croata que ha destacado en varias posiciones en la escena competitiva. Ha competido en múltiples campeonatos mundiales." },
  { id: 28, nombre: "Park Jae-hyuk<br />(Ruler)", deporte: "League of Legends", equipo: "Gen.G", equipo_url: "https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Gen.G_Logo.svg/1200px-Gen.G_Logo.svg.png" ,posicion: "AD Carry", valoracion: 3, url: "https://cdn.oneesports.gg/cdn-data/2022/03/LeagueOfLegends_GenG_Ruler-1.jpg " ,biografia: "Ruler es un destacado AD Carry coreano conocido por su habilidad y consistencia. Ha competido en campeonatos mundiales y ha sido un pilar para su equipo." },
  // { id: 29, nombre: "Kim Tae-sang<br />(Doinb)", deporte: "League of Legends", equipo: "FunPlus Phoenix", equipo_url: "" ,posicion: "Midlaner", valoracion: 3, url: " " ,biografia: "Doinb es un Midlaner coreano conocido por su estilo de juego único y su capacidad para liderar a su equipo. Ha sido campeón mundial y ha dejado una huella en la escena competitiva." },
  // { id: 30, nombre: "Hung Hau-Hsuan<br />(Karsa)", deporte: "League of Legends", equipo: "Royal Never Give Up", equipo_url: "" ,posicion: "Jungla", valoracion: 3, url: " " ,biografia: "Karsa es un talentoso jugador taiwanés que ha demostrado su habilidad en la jungla. Ha competido en campeonatos mundiales y ha sido un elemento clave para su equipo." },
  { id: 32, nombre: "Kim Dong-ha<br />(Khan)", deporte: "League of Legends", equipo: "DWG KIA", equipo_url: "https://esports.as.com/2021/09/29/DWG_KIAlogo_square.png?hash=3e554ecbaa2034e8515c56d6c6b3b0d160514f47" ,posicion: "Toplaner", valoracion: 3, url: "https://i1.wp.com/historia-biografia.com/wp-content/uploads/2021/05/khanlol.jpg?fit=1000%2C450&ssl=1 " ,biografia: "Khan es un reconocido Toplaner coreano conocido por su agresividad y capacidad para llevar a su equipo a la victoria. Ha competido en campeonatos mundiales y ha dejado su huella." }
]];

export default Datos;


